//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AytoLosLLanos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion
    {
        public Estacion()
        {
            this.Estacion_Propietario = new HashSet<Estacion_Propietario>();
            this.Tipoes = new HashSet<Tipo>();
        }
    
        public int IdEstacion { get; set; }
        public string Nombre { get; set; }
        public string Alias { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<int> IdTabla { get; set; }
        public string Descripcion { get; set; }
        public string PrimerRegistro { get; set; }
        public string UltimoRegistro { get; set; }
    
        public virtual ICollection<Estacion_Propietario> Estacion_Propietario { get; set; }
        public virtual Tabla Tabla { get; set; }
        public virtual ICollection<Tipo> Tipoes { get; set; }
    }
}
