//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AytoLosLLanos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion_Propietario
    {
        public int Id { get; set; }
        public int IdEstacion { get; set; }
        public int IdPropietario { get; set; }
    
        public virtual Estacion Estacion { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
