//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AytoLosLLanos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        public Propietario()
        {
            this.Estacion_Propietario = new HashSet<Estacion_Propietario>();
        }
    
        public int IdPropietario { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Alias { get; set; }
        public Nullable<int> Conexiones { get; set; }
    
        public virtual ICollection<Estacion_Propietario> Estacion_Propietario { get; set; }
    }
}
