//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AytoLosLLanos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public int IdTipo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Canal { get; set; }
        public Nullable<double> Factor { get; set; }
        public Nullable<int> IdEstacion { get; set; }
    
        public virtual Estacion Estacion { get; set; }
    }
}
